### ISSUE TITLE
this module doesn't seem to work at all

### ISSUE THREAD

**Issue by tjwebb** [repo-utils/org-labels#15]
after authenticating, the tool runs, spits out some random 404, and then makes no changes anywhere
```
$ org-labels remove trailsjs bug
GitHub rate limit remaining: 4845
found 26 repositories in trailsjs

Error: 404 - https://api.github.com/repos/trailsjs/badgeboard/labels/bug
```

if I make a get request in my browser for that label, I see it:

```
{
  "url": "https://api.github.com/repos/trailsjs/badgeboard/labels/bug",
  "name": "bug",
  "color": "fc2929"
}
```

**Comment by Fishrock123** [comment]
@tjwebb Hmmm, I haven't check this in quite some time, I don't think GitHub changed their API but it is possible that they did.

**Comment by tjwebb** [comment]
Hey @Fishrock123 I got it working though I don't remember how. Sorry for the useless issue :(

**Comment by Fishrock123** [comment]
@tjwebb if you had to make an edit to the module, could you post the diff?
